

CREATE DATABASE IF NOT EXISTS teamsoft;
USE teamsoft;

CREATE TABLE IF NOT EXISTS recetas (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    recipe TEXT NOT NULL
);


GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '316170040' WITH GRANT OPTION;
FLUSH PRIVILEGES;


