on:
  push:
    branches:
      - main

name: deploy

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: "bigredrocketoflove"
          password: "316170040-RHk"
          repository: "bigredrocketoflove/lemp"
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
